openapi: 3.0.0
info:
  title: IdeaXAPI 
  description: An Api to generate cool ideas for your next project or maybe startup
  version: 1.0.0
servers:
  - url: https://idea-x-api.vercel.app
paths:
  /api/idea:
    get:
      summary: Get a random project idea
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { "idea": "Create a mobile app for language learning." }

  /api/idea/mentor:
    get:
      summary: Get a project idea based on a mentor's name
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: The name of your mentor
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { "idea": "Build a website to showcase your mentor's expertise." }
  
  /api/idea/talkmentor:
    get:
      summary: Generate Idea
      description: |
        Generates an idea based on the provided mentor name and user text.
      parameters:
        - name: name
          in: query
          description: The name of the mentor.
          required: true
          schema:
            type: string
        - name: usertext
          in: query
          description: The user's text to generate the idea.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response with the generated idea.
          content:
            application/json:
              schema:
                type: object
                properties:
                  idea:
                    type: string
                    description: The generated idea.
  /:
    get:
      summary: Home endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              example: "Welcome to the Random Project Generator API!"
